AWSTemplateFormatVersion: "2010-09-09"

Description: Deploys the Voicemail Express Lambda functions.

Parameters:
  EXPTemplateVersion:
    Type: String
  AWSRegion:
    Type: String
  ConnectInstanceAlias:
    Type: String
  EnableVMToConnectTask:
    Type: String
  EnableVMToEmail:
    Type: String
  EXPDevBucketPrefix:
    Type: String
  LambdaLoggingLevel:
    Type: String
  RecordingsExpireInXDays:
    Type: String
  VMEmailDefaultAgentTemplate:
    Type: String
  VMEmailDefaultQueueTemplate:
    Type: String
  VMDefaultMode:
    Type: String
  VMToEmailDefaultFrom:
    Type: String
  VMToEmailDefaultTo:
    Type: String
  VMXDefaultTaskFlow:
    Type: String
  VMXSecrets:
    Type: String
  VMXCoreRoleArn:
    Type: String
  VMXCoreRole:
    Type: String
  VMXS3RecordingsBucket:
    Type: String
  VMXS3TranscriptsBucket:
    Type: String

Mappings:
  TZInfo:
    us-east-1:
      TZvalue: 'America/New_York'
    us-west-2:
      TZvalue: 'America/Los_Angeles'
    af-south-1:
      TZvalue: 'Africa/Johannesburg'
    ap-southeast-1:
      TZvalue: 'Asia/Singapore'
    ap-southeast-2:
      TZvalue: 'Australia/Sydney'
    ap-northeast-1:
      TZvalue: 'Asia/Tokyo'
    ap-northeast-2:
      TZvalue: 'Asia/Seoul'
    ca-central-1:
      TZvalue: 'Canada/Central'
    eu-central-1:
      TZvalue: 'Europe/Berlin'
    eu-west-2:
      TZvalue: 'Europe/London'
  VMModes:
    AmazonConnectTask:
      mode: task
    AmazonSimpleEmailService:
      mode: email

Conditions:
  ConnectTasksEnabled: !Equals [!Ref EnableVMToConnectTask, yes]
  AWSEmailEnabled: !Equals [!Ref EnableVMToEmail, yes]

Resources:
  VMXPythonLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.11
      Content:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_common_python.zip
      Description: Provides dependencies code and functions for Python Lambda functions that augment the Service Cloud Voice offering from Salesforce
      LayerName: !Join
        - ''
        - - 'common_python_layer_'
          - !Ref ConnectInstanceAlias
      LicenseInfo: https://aws.amazon.com/apache-2-0

  VMXPresigner:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_presigner.py.zip
      Description: Generates the presigned URL that provides authenticated access to the voicemail recording in S3
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_obj_lifecycle:
            Ref: RecordingsExpireInXDays
          secrets_key_id:
            Ref: VMXSecrets
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'VMX3-Presigner-'
              - !Ref ConnectInstanceAlias
      Handler: vmx3_presigner.lambda_handler
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Role: !Ref VMXCoreRoleArn
      Runtime: python3.12
      Timeout: 30

  VMXPackager:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_packager.py.zip
      Description: Packages the voicemail and creates a task in Amazon Connect.
      Environment:
        Variables:
          s3_recordings_bucket:
            Ref: VMXS3RecordingsBucket
          s3_transcripts_bucket:
            Ref: VMXS3TranscriptsBucket
          presigner_function_arn:
            Ref: VMXPresigner
          default_task_flow:
            !If [ConnectTasksEnabled, !Ref VMXDefaultTaskFlow, 'AWS::NoValue']
          package_version:
            Ref: EXPTemplateVersion
          TZ:
            !FindInMap [TZInfo, !Ref "AWS::Region", TZvalue]
          default_email_from:
            !If [AWSEmailEnabled, !Ref VMToEmailDefaultFrom, 'AWS::NoValue']
          default_email_target:
            !If [AWSEmailEnabled, !Ref VMToEmailDefaultTo, 'AWS::NoValue']
          default_vmx_mode:
            !FindInMap [VMModes, !Ref "VMDefaultMode", mode]
          default_agent_email_template:
            !If [AWSEmailEnabled, !Ref VMEmailDefaultAgentTemplate, 'AWS::NoValue']
          default_queue_email_template:
            !If [AWSEmailEnabled, !Ref VMEmailDefaultQueueTemplate, 'AWS::NoValue']
      FunctionName:
        !Join
            - ''
            - - 'VMX3-Packager-'
              - !Ref ConnectInstanceAlias
      Handler: vmx3_packager.lambda_handler
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Role: !Ref VMXCoreRoleArn
      Layers: [!Ref VMXPythonLayer]
      Runtime: python3.12
      Timeout: 900

  VMXTranscriber:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_transcriber.py.zip
      Description: Transcribes the voicemail to text and stores the transcription in S3
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_transcripts_bucket:
            Ref: VMXS3TranscriptsBucket
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'VMX3-Transcriber-'
              - !Ref ConnectInstanceAlias
      Handler: vmx3_transcriber.lambda_handler
      Role: !Ref VMXCoreRoleArn
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 900

  VMXKVStoS3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_kvs_to_s3.py.zip
      Description: Extracts the voicemail from the KVS stream and writes it to S3 with tag data
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_recordings_bucket:
            Ref: VMXS3RecordingsBucket
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'VMX3-KVStoS3-'
              - !Ref ConnectInstanceAlias
      Handler: vmx3_kvs_to_s3.lambda_handler
      Role: !Ref VMXCoreRoleArn
      Layers: [!Ref VMXPythonLayer]
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 900

  VMXTranscribeErrorHandler:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          !Join
            - ''
            - - !Ref EXPDevBucketPrefix
              - 'vmx-source-'
              - !Ref AWSRegion
        S3Key:
          !Join
          - ''
          - - 'vmx3/'
            - !Ref EXPTemplateVersion
            - /zip/vmx3_transcription_error_handler.py.zip
      Description: Catches transcription errors due to corrupt wav files and provides a notification transcript so that processing completes
      Environment:
        Variables:
          aws_region:
            Ref: AWSRegion
          s3_transcripts_bucket:
            Ref: VMXS3TranscriptsBucket
          package_version:
            Ref: EXPTemplateVersion
      FunctionName:
        !Join
            - ''
            - - 'VMX3-TranscribeErrorHandler-'
              - !Ref ConnectInstanceAlias
      Handler: vmx3_transcription_error_handler.lambda_handler
      Role: !Ref VMXCoreRoleArn
      Runtime: python3.12
      LoggingConfig:
        ApplicationLogLevel:
          Ref: LambdaLoggingLevel
        LogFormat: JSON
        SystemLogLevel: INFO
      Timeout: 30

  VMXAddOnPolicy:
    Type: AWS::IAM::ManagedPolicy
    DependsOn:
        - VMXPresigner
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'lambda:InvokeFunction'
            Resource:
              - !GetAtt VMXPresigner.Arn
          - Effect: Allow
            Action:
              - 'transcribe:StartTranscriptionJob'
              - 'transcribe:DeleteTranscriptionJob'
              - 'connect:DescribeUser'
              - 'connect:UpdateContactAttributes'
              - 'connect:GetContactAttributes'
              - 'connect:DescribeQueue'
              - 'connect:StartTaskContact'
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - 'secretsmanager:GetSecretValue'
              - 'secretsmanager:DescribeSecret'
              - 'secretsmanager:ListSecretVersionIds'
            Resource:
              - !Ref VMXSecrets
      ManagedPolicyName:
        !Join
          - ''
          - - 'VMXCorePolicy-'
            - !Ref ConnectInstanceAlias
      Roles:
        - !Ref VMXCoreRole

Outputs:
  VMXPackagerArn:
    Description: ARN of the Packager function
    Value: !GetAtt VMXPackager.Arn
  VMXTranscriberArn:
    Description: ARN of the Transcriber function
    Value: !GetAtt VMXTranscriber.Arn
  VMXKVStoS3:
    Description: Name of the KVS to S3 function
    Value: !Ref VMXKVStoS3
  VMXTranscribeErrorArn:
    Description: ARN of the transcribe error handler function
    Value: !GetAtt VMXTranscribeErrorHandler.Arn